[tool.black]
line-length = 79
target-version = ['py36', 'py37']
include = '\.pyi?$'
exclude = '''
/(
  # generic
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist

  # django
  | migrations
)/
'''
